In [1]:
import numpy as np  
import matplotlib.pyplot as plt
import pandas as pd
import xarray as xr
import os
import SeaLevelContrib as slc

/Users/dewilebars/anaconda3/envs/p37ds/lib/python3.7/site-packages/xarray/core/merge.py:17: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)


In [ ]:
importlib.reload(slc)

In [3]:
data = xr.DataArray(np.random.randn(2, 3), coords={'x': ['a', 'b']}, dims=('x', 'y'))
print(data)

<xarray.DataArray (x: 2, y: 3)>
array([[ 0.826907, -0.159959, -0.214182],
       [-0.703492, -1.600494,  0.876384]])
Coordinates:
  * x        (x) <U1 'a' 'b'
Dimensions without coordinates: y


In [4]:
labels = xr.DataArray(['E', 'F', 'E'], [data.coords['y']], name='labels')
data.groupby(labels).mean('y')

<xarray.DataArray (x: 2, labels: 2)>
array([[ 0.306363, -0.159959],
       [ 0.086446, -1.600494]])
Coordinates:
  * x        (x) <U1 'a' 'b'
  * labels   (labels) object 'E' 'F'

In [5]:
ds = xr.Dataset({'foo': data, 'bar': ('x', [1, 2]), 'baz': np.pi})
ds.to_netcdf('example.nc')
xr.open_dataset('example.nc')
print(xr)
os.system('rm example.nc')

/anaconda3/lib/python3.6/site-packages/dask/utils.py:1010: UserWarning: Deprecated, see dask.base.get_scheduler instead
  warnings.warn("Deprecated, see dask.base.get_scheduler instead")


<module 'xarray' from '/anaconda3/lib/python3.6/site-packages/xarray/__init__.py'>


0

In [6]:
A = np.array([1, 2, 3, 3, np.nan, np.nan])
unique, counts = np.unique(A, return_counts=True)
print(np.asarray((unique, counts)).T)
np.bitwise_not(np.isnan(A))
np.mean(A)

[[ 1.  1.]
 [ 2.  1.]
 [ 3.  2.]
 [nan  1.]
 [nan  1.]]


nan

In [7]:
data = xr.DataArray(np.random.randn(2, 3), coords={'x': ['a', 'b']}, dims=('x', 'y'))
data[0,0] = np.nan
print(data)
#data[ np.isnan(data) ] = 1
data2 = xr.where(np.isnan(data), data, 1)
print(data2)

<xarray.DataArray (x: 2, y: 3)>
array([[      nan, -2.300024, -0.82257 ],
       [-1.023594, -0.965895, -0.860688]])
Coordinates:
  * x        (x) <U1 'a' 'b'
Dimensions without coordinates: y
<xarray.DataArray (x: 2, y: 3)>
array([[nan,  1.,  1.],
       [ 1.,  1.,  1.]])
Coordinates:
  * x        (x) <U1 'a' 'b'
Dimensions without coordinates: y


In [8]:
data3 = xr.DataArray(np.random.randn(3), dims=('y'))
data4 = np.sum(data2 * data3)
data4

<xarray.DataArray ()>
array(4.34815)

In [13]:
npa = np.array(np.random.randn(2,3))
#npa = xr.DataArray(npa, dims=('x','y'))
npa2 = xr.DataArray(np.random.randn(3))
npa3 = np.sum(npa * npa2)
npa3

ValueError: applied function returned data with unexpected number of dimensions: 2 vs 1, for dimensions ('dim_0',)

In [37]:
u = np.array(np.arange(6)-3)
print(u)
u2 = u**2 * np.sign(u)
u2

[-3 -2 -1  0  1  2]


array([-9, -4, -1,  0,  1,  4])

In [ ]:
u_file = 'http://www.esrl.noaa.gov/psd/thredds/dodsC/Datasets/ncep.reanalysis.derived/surface_gauss/uwnd.10m.mon.mean.nc'
ds_u = netCDF4.Dataset(u_file)

